BAD_NAMES = [
    "MECHANICAL_DESIGN_GEOMETRIC_PRESENTATION_REPRESENTATION",
    "SHAPE_DEFINITION_REPRESENTATION",
    "PROPERTY_DEFINITION_REPRESENTATION",
    "REPRESENTATION",
    "PROPERTY_DEFINITION",
    "VALUE_REPRESENTATION_ITEM",
    "SHAPE_REPRESENTATION_RELATIONSHIP",
    "ADVANCED_BREP_SHAPE_REPRESENTATION"
]

CORRECT_ORDER = [
    "CARTESIAN_POINT",
    "DIRECTION",
    "AXIS2_PLACEMENT_3D",
    "PLANE",
    "VECTOR",
    "LINE",
    "VERTEX_POINT",
    "B_SPLINE_CURVE_WITH_KNOTS",
    "CIRCLE",
    #"EDGE_CURVE",
]