PLOT_ORDER = [
    #"CIRCLE",
    #"B_SPLINE_CURVE_WITH_KNOTS",
    #"CONICAL_SURFACE",
    #"CYLINDRICAL_SURFACE",
    #"TOROIDAL_SURFACE",
    #"ORIENTED_EDGE",
    "EDGE_LOOP"
]

NUMBER_OF_TOR_SURFACE_POINTS = 40
NUMBER_OF_CYL_SURFACE_POINTS = 40
NUMBER_OF_CON_SURFACE_POINTS = 40

